export const linkedinLink = "https://www.linkedin.com/in/sneha-kumari-674662274"
export const twitterLink = "#"
export const instagramLink = "#"
export const mailLink = "mailto:sneha001705@gmail.com"
export const githubLink = "https://github.com/Snehaaa-Kri"
